export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",
};

export const productDetailsConstants = {
  GET_SINGLE_PRODUCT_REQUEST: "GET_SINGLE_PRODUCT_REQUEST",
  GET_SINGLE_PRODUCT_SUCCESS: "GET_SINGLE_PRODUCT_SUCCESS",
  GET_SINGLE_PRODUCT_FAILURE: "GET_SINGLE_PRODUCT_FAILURE",
};

export const cartConstants = {
  ADD_CART_ITEM_REQUEST: "ADD_CART_ITEM_REQUEST",
  ADD_CART_ITEM_SUCCESS: "ADD_CART_ITEM_SUCCESS",
  ADD_CART_ITEM_FAILURE: "ADD_CART_ITEM_FAILURE",

  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",
};
