export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",
};

export const productDetailsConstants = {
  GET_SINGLE_PRODUCT_REQUEST: "GET_SINGLE_PRODUCT_REQUEST",
  GET_SINGLE_PRODUCT_SUCCESS: "GET_SINGLE_PRODUCT_SUCCESS",
  GET_SINGLE_PRODUCT_FAILURE: "GET_SINGLE_PRODUCT_FAILURE",
};

export const cartConstants = {
  ADD_CART_ITEM_REQUEST: "ADD_CART_ITEM_REQUEST",
  ADD_CART_ITEM_SUCCESS: "ADD_CART_ITEM_SUCCESS",
  ADD_CART_ITEM_FAILURE: "ADD_CART_ITEM_FAILURE",

  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",

  CART_SAVE_SHIPPING_ADDRESS_REQUEST: "CART_SAVE_SHIPPING_ADDRESS_REQUEST",
  CART_SAVE_SHIPPING_ADDRESS_SUCCESS: "CART_SAVE_SHIPPING_ADDRESS_SUCCESS",
  CART_SAVE_SHIPPING_ADDRESS_FAILURE: "CART_SAVE_SHIPPING_ADDRESS_FAILURE",

  CART_SAVE_PAYMENT_METHOD_REQUEST: "CART_SAVE_PAYMENT_METHOD_REQUEST",
  CART_SAVE_PAYMENT_METHOD_SUCCESS: "CART_SAVE_PAYMENT_METHOD_SUCCESS",
  CART_SAVE_PAYMENT_METHOD_FAILURE: "CART_SAVE_PAYMENT_METHOD_FAILURE",
};

export const userConstants = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  USER_LOGOUT_REQUEST: "USER_LOGOUT_REQUEST",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE",

  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",

  USER_DETAILS_REQUEST: "USER_DETAILS_REQUEST",
  USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
  USER_DETAILS_FAILURE: "USER_DETAILS_FAILURE",

  USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  USER_UPDATE_FAILURE: "USER_UPDATE_FAILURE",
};
