export const productConstants = {
  GET_ALL_PRODUCT_REQUEST: "GET_ALL_PRODUCT_REQUEST",
  GET_ALL_PRODUCT_SUCCESS: "GET_ALL_PRODUCT_SUCCESS",
  GET_ALL_PRODUCT_FAILURE: "GET_ALL_PRODUCT_FAILURE",

  // Private/Admin constants
  REMOVE_PRODUCT_REQUEST: "REMOVE_PRODUCT_REQUEST",
  REMOVE_PRODUCT_SUCCESS: "REMOVE_PRODUCT_SUCCESS",
  REMOVE_PRODUCT_FAILURE: "REMOVE_PRODUCT_FAILURE",

  UPDATE_PRODUCT_REQUEST: "UPDATE_PRODUCT_REQUEST",
  UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
  UPDATE_PRODUCT_FAILURE: "UPDATE_PRODUCT_FAILURE",
  UPDATE_PRODUCT_RESET: "UPDATE_PRODUCT_RESET",
};

export const productDetailsConstants = {
  GET_SINGLE_PRODUCT_REQUEST: "GET_SINGLE_PRODUCT_REQUEST",
  GET_SINGLE_PRODUCT_SUCCESS: "GET_SINGLE_PRODUCT_SUCCESS",
  GET_SINGLE_PRODUCT_FAILURE: "GET_SINGLE_PRODUCT_FAILURE",

  CREATE_PRODUCT_REQUEST: "CREATE_PRODUCT_REQUEST",
  CREATE_PRODUCT_SUCCESS: "CREATE_PRODUCT_SUCCESS",
  CREATE_PRODUCT_FAILURE: "CREATE_PRODUCT_FAILURE",
  CREATE_PRODUCT_RESET: "CREATE_PRODUCT_RESET",
};

export const cartConstants = {
  ADD_CART_ITEM_REQUEST: "ADD_CART_ITEM_REQUEST",
  ADD_CART_ITEM_SUCCESS: "ADD_CART_ITEM_SUCCESS",
  ADD_CART_ITEM_FAILURE: "ADD_CART_ITEM_FAILURE",

  REMOVE_CART_ITEM_REQUEST: "REMOVE_CART_ITEM_REQUEST",
  REMOVE_CART_ITEM_SUCCESS: "REMOVE_CART_ITEM_SUCCESS",
  REMOVE_CART_ITEM_FAILURE: "REMOVE_CART_ITEM_FAILURE",

  CART_SAVE_SHIPPING_ADDRESS_REQUEST: "CART_SAVE_SHIPPING_ADDRESS_REQUEST",
  CART_SAVE_SHIPPING_ADDRESS_SUCCESS: "CART_SAVE_SHIPPING_ADDRESS_SUCCESS",
  CART_SAVE_SHIPPING_ADDRESS_FAILURE: "CART_SAVE_SHIPPING_ADDRESS_FAILURE",

  CART_SAVE_PAYMENT_METHOD_REQUEST: "CART_SAVE_PAYMENT_METHOD_REQUEST",
  CART_SAVE_PAYMENT_METHOD_SUCCESS: "CART_SAVE_PAYMENT_METHOD_SUCCESS",
  CART_SAVE_PAYMENT_METHOD_FAILURE: "CART_SAVE_PAYMENT_METHOD_FAILURE",
};

export const userConstants = {
  USER_LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE: "USER_LOGIN_FAILURE",

  USER_LOGOUT_REQUEST: "USER_LOGOUT_REQUEST",
  USER_LOGOUT_SUCCESS: "USER_LOGOUT_SUCCESS",
  USER_LOGOUT_FAILURE: "USER_LOGOUT_FAILURE",

  USER_REGISTER_REQUEST: "USER_REGISTER_REQUEST",
  USER_REGISTER_SUCCESS: "USER_REGISTER_SUCCESS",
  USER_REGISTER_FAILURE: "USER_REGISTER_FAILURE",

  USER_PROFILE_REQUEST: "USER_PROFILE_REQUEST",
  USER_PROFILE_SUCCESS: "USER_PROFILE_SUCCESS",
  USER_PROFILE_FAILURE: "USER_PROFILE_FAILURE",
  USER_PROFILE_RESET: "USER_PROFILE_RESET",

  USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  USER_UPDATE_FAILURE: "USER_UPDATE_FAILURE",

  USER_LIST_REQUEST: "USER_LIST_REQUEST",
  USER_LIST_SUCCESS: "USER_LIST_SUCCESS",
  USER_LIST_FAILURE: "USER_LIST_FAILURE",
  USER_LIST_RESET: "USER_LIST_RESET",

  // user delete admin
  USER_DELETE_REQUEST: "USER_DELETE_REQUEST",
  USER_DELETE_SUCCESS: "USER_DELETE_SUCCESS",
  USER_DELETE_FAILURE: "USER_DELETE_FAILURE",
  USER_DELETE_RESET: "USER_DELETE_RESET",

  // user details admin
  USER_DETAILS_REQUEST: "USER_DETAILS_REQUEST",
  USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
  USER_DETAILS_FAILURE: "USER_DETAILS_FAILURE",
  USER_DETAILS_RESET: "USER_DETAILS_RESET",

  // user update admin
  USER_DETAILS_UPDATE_REQUEST: "USER_DETAILS_UPDATE_REQUEST",
  USER_DETAILS_UPDATE_SUCCESS: "USER_DETAILS_UPDATE_SUCCESS",
  USER_DETAILS_UPDATE_FAILURE: "USER_DETAILS_UPDATE_FAILURE",
  USER_DETAILS_UPDATE_RESET: "USER_DETAILS_UPDATE_RESET",
};

export const orderConstants = {
  ORDER_CREATE_REQUEST: "ORDER_CREATE_REQUEST",
  ORDER_CREATE_SUCCESS: "ORDER_CREATE_SUCCESS",
  ORDER_CREATE_FAILURE: "ORDER_CREATE_FAILURE",

  ORDER_DETAILS_REQUEST: "ORDER_DETAILS_REQUEST",
  ORDER_DETAILS_SUCCESS: "ORDER_DETAILS_SUCCESS",
  ORDER_DETAILS_FAILURE: "ORDER_DETAILS_FAILURE",

  ORDER_PAY_REQUEST: "ORDER_PAY_REQUEST",
  ORDER_PAY_SUCCESS: "ORDER_PAY_SUCCESS",
  ORDER_PAY_FAILURE: "ORDER_PAY_FAILURE",
  ORDER_PAY_RESET: "ORDER_PAY_RESET",

  // ORDER LIST OF LOGGED IN USER
  ORDER_LIST_REQUEST: "ORDER_LIST_REQUEST",
  ORDER_LIST_SUCCESS: "ORDER_LIST_SUCCESS",
  ORDER_LIST_FAILURE: "ORDER_LIST_FAILURE",
  ORDER_LIST_RESET: "ORDER_LIST_RESET",

  // Private/Admin
  ORDER_GET_ALL_REQUEST: "ORDER_GET_ALL_REQUEST",
  ORDER_GET_ALL_SUCCESS: "ORDER_GET_ALL_SUCCESS",
  ORDER_GET_ALL_FAILURE: "ORDER_GET_ALL_FAILURE",

  ORDER_UPDATE_TO_DELIVER_REQUEST: "ORDER_UPDATE_TO_DELIVER_REQUEST",
  ORDER_UPDATE_TO_DELIVER_SUCCESS: "ORDER_UPDATE_TO_DELIVER_SUCCESS",
  ORDER_UPDATE_TO_DELIVER_FAILURE: "ORDER_UPDATE_TO_FAILURE",
  ORDER_UPDATE_TO_DELIVER_RESET: "ORDER_UPDATE_TO_RESET",
};
